sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default libqt5svg5-dev qtmultimedia5-dev

script:
  - mkdir build
  - cd build
  - qmake ..
  - make

