sudo: required

dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qt5-default libqt5svg5-dev

script:
  - export QMAKE_CC=$CC
  - export QMAKE_CXX=$CXX
  - mkdir build
  - cd build
  - qmake ..
  - make

